#ifndef OPENLWM2M_CONFIG_HPP_
#define OPENLWM2M_CONFIG_HPP_

#define CONFIG_LOG_LEVEL LOG_LEVEL_DEBUG

#define CONFIG_MINIMAL_CLIENT 0

#define CONFIG_BOOTSTRAP_SERVER 1

#define CONFIG_DEFAULT_STRING_LEN 255

#define CONFIG_BINDING_STR_MAX_LEN 4

#define CONFIG_LIFETIME_SCALE 0.9

#define CONFIG_NUM_SERVERS 2

#define CONFIG_CLIENT_PUBLIC_KEY_MAX_LEN 32

#define CONFIG_SERVER_PUBLIC_KEY_MAX_LEN 32

#define CONFIG_CLIENT_PRIVATE_KEY_MAX_LEN 32

#define CONFIG_ERR_CODE_MAX_SIZE 4

#define CONFIG_DEFAULT_DATA_FORMAT DATA_FMT_SENML_JSON

#endif /* OPENLWM2M_CONFIG_HPP_ */
