#ifndef OPENLWM2M_CONFIG_HPP_
#define OPENLWM2M_CONFIG_HPP_

#define CONFIG_LOG_LEVEL LOG_LEVEL_DEBUG

#define CONFIG_MAX_OBJ_SECURITY 2
#define CONFIG_MAX_OBJ_SERVER 2

#endif /* OPENLWM2M_CONFIG_HPP_ */
